/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ufps.poo2.ejercicio.banco.vista;

import ufps.poo2.ejercicio.banco.controlador.BancoControlador;

/**
 *
 * @author Boris Perez
 */
public class BancoVista extends javax.swing.JFrame {
    private BancoControlador controller;
    /**
     * Creates new form BancoVista
     */
    public BancoVista() {
        initComponents();
        controller = new BancoControlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupAcciones = new javax.swing.ButtonGroup();
        btnGrpMascota = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtSaldoCuenta = new javax.swing.JTextField();
        rbAhorros = new javax.swing.JRadioButton();
        rbCorriente = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroCuentaAcciones = new javax.swing.JTextField();
        rbDividendos = new javax.swing.JRadioButton();
        rbRetirar = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnCancelarAcciones = new javax.swing.JButton();
        btnAplicar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensajes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnCorreos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Núm. cuenta:");

        jLabel2.setText("Saldo: $");

        txtNumeroCuenta.setToolTipText("");

        buttonGroup1.add(rbAhorros);
        rbAhorros.setText("Cta. Ahorros");
        rbAhorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAhorrosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCorriente);
        rbCorriente.setText("Cta. Corriente");
        rbCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCorrienteActionPerformed(evt);
            }
        });

        btnCrear.setText("Abrir");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrear))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rbAhorros)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbCorriente))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAhorros)
                    .addComponent(rbCorriente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Núm. cuenta:");

        txtNumeroCuentaAcciones.setToolTipText("");

        buttonGroupAcciones.add(rbDividendos);
        rbDividendos.setText("Pagar dividendos");

        buttonGroupAcciones.add(rbRetirar);
        rbRetirar.setText("Retirar");

        jLabel4.setText("Valor: $");

        btnCancelarAcciones.setText("Cancelar");
        btnCancelarAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAccionesActionPerformed(evt);
            }
        });

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbDividendos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbRetirar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroCuentaAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancelarAcciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAplicar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroCuentaAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDividendos)
                    .addComponent(rbRetirar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicar)
                    .addComponent(btnCancelarAcciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taMensajes.setColumns(20);
        taMensajes.setRows(5);
        jScrollPane1.setViewportView(taMensajes);

        jLabel5.setText("Estado de operaciones");

        btnCorreos.setText("Enviar correos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCorreos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(btnCorreos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCorrienteActionPerformed

    private void rbAhorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAhorrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAhorrosActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        controller.abrirCuenta();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controller.cancelarCuenta();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        controller.aplicar();
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnCancelarAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAccionesActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_btnCancelarAccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarAcciones;
    private javax.swing.JButton btnCorreos;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup btnGrpMascota;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupAcciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAhorros;
    private javax.swing.JRadioButton rbCorriente;
    private javax.swing.JRadioButton rbDividendos;
    private javax.swing.JRadioButton rbRetirar;
    private javax.swing.JTextArea taMensajes;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroCuentaAcciones;
    private javax.swing.JTextField txtSaldoCuenta;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controller
     */
    public BancoControlador getController() {
        return controller;
    }

    /**
     * @param controller the controller to set
     */
    public void setController(BancoControlador controller) {
        this.controller = controller;
    }

    /**
     * @return the btnAplicar
     */
    public javax.swing.JButton getBtnAplicar() {
        return btnAplicar;
    }

    /**
     * @param btnAplicar the btnAplicar to set
     */
    public void setBtnAplicar(javax.swing.JButton btnAplicar) {
        this.btnAplicar = btnAplicar;
    }

    /**
     * @return the btnCancelar
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @param btnCancelar the btnCancelar to set
     */
    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    /**
     * @return the btnCancelarAcciones
     */
    public javax.swing.JButton getBtnCancelarAcciones() {
        return btnCancelarAcciones;
    }

    /**
     * @param btnCancelarAcciones the btnCancelarAcciones to set
     */
    public void setBtnCancelarAcciones(javax.swing.JButton btnCancelarAcciones) {
        this.btnCancelarAcciones = btnCancelarAcciones;
    }

    /**
     * @return the btnCorreos
     */
    public javax.swing.JButton getBtnCorreos() {
        return btnCorreos;
    }

    /**
     * @param btnCorreos the btnCorreos to set
     */
    public void setBtnCorreos(javax.swing.JButton btnCorreos) {
        this.btnCorreos = btnCorreos;
    }

    /**
     * @return the btnCrear
     */
    public javax.swing.JButton getBtnCrear() {
        return btnCrear;
    }

    /**
     * @param btnCrear the btnCrear to set
     */
    public void setBtnCrear(javax.swing.JButton btnCrear) {
        this.btnCrear = btnCrear;
    }

    /**
     * @return the btnGrpMascota
     */
    public javax.swing.ButtonGroup getBtnGrpMascota() {
        return btnGrpMascota;
    }

    /**
     * @param btnGrpMascota the btnGrpMascota to set
     */
    public void setBtnGrpMascota(javax.swing.ButtonGroup btnGrpMascota) {
        this.btnGrpMascota = btnGrpMascota;
    }

    /**
     * @return the buttonGroup1
     */
    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    /**
     * @param buttonGroup1 the buttonGroup1 to set
     */
    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    /**
     * @return the buttonGroupAcciones
     */
    public javax.swing.ButtonGroup getButtonGroupAcciones() {
        return buttonGroupAcciones;
    }

    /**
     * @param buttonGroupAcciones the buttonGroupAcciones to set
     */
    public void setButtonGroupAcciones(javax.swing.ButtonGroup buttonGroupAcciones) {
        this.buttonGroupAcciones = buttonGroupAcciones;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the rbAhorros
     */
    public javax.swing.JRadioButton getRbAhorros() {
        return rbAhorros;
    }

    /**
     * @param rbAhorros the rbAhorros to set
     */
    public void setRbAhorros(javax.swing.JRadioButton rbAhorros) {
        this.rbAhorros = rbAhorros;
    }

    /**
     * @return the rbCorriente
     */
    public javax.swing.JRadioButton getRbCorriente() {
        return rbCorriente;
    }

    /**
     * @param rbCorriente the rbCorriente to set
     */
    public void setRbCorriente(javax.swing.JRadioButton rbCorriente) {
        this.rbCorriente = rbCorriente;
    }

    /**
     * @return the rbDividendos
     */
    public javax.swing.JRadioButton getRbDividendos() {
        return rbDividendos;
    }

    /**
     * @param rbDividendos the rbDividendos to set
     */
    public void setRbDividendos(javax.swing.JRadioButton rbDividendos) {
        this.rbDividendos = rbDividendos;
    }

    /**
     * @return the rbRetirar
     */
    public javax.swing.JRadioButton getRbRetirar() {
        return rbRetirar;
    }

    /**
     * @param rbRetirar the rbRetirar to set
     */
    public void setRbRetirar(javax.swing.JRadioButton rbRetirar) {
        this.rbRetirar = rbRetirar;
    }

    /**
     * @return the taMensajes
     */
    public javax.swing.JTextArea getTaMensajes() {
        return taMensajes;
    }

    /**
     * @param taMensajes the taMensajes to set
     */
    public void setTaMensajes(javax.swing.JTextArea taMensajes) {
        this.taMensajes = taMensajes;
    }

    /**
     * @return the txtNumeroCuenta
     */
    public javax.swing.JTextField getTxtNumeroCuenta() {
        return txtNumeroCuenta;
    }

    /**
     * @param txtNumeroCuenta the txtNumeroCuenta to set
     */
    public void setTxtNumeroCuenta(javax.swing.JTextField txtNumeroCuenta) {
        this.txtNumeroCuenta = txtNumeroCuenta;
    }

    /**
     * @return the txtNumeroCuentaAcciones
     */
    public javax.swing.JTextField getTxtNumeroCuentaAcciones() {
        return txtNumeroCuentaAcciones;
    }

    /**
     * @param txtNumeroCuentaAcciones the txtNumeroCuentaAcciones to set
     */
    public void setTxtNumeroCuentaAcciones(javax.swing.JTextField txtNumeroCuentaAcciones) {
        this.txtNumeroCuentaAcciones = txtNumeroCuentaAcciones;
    }

    /**
     * @return the txtSaldoCuenta
     */
    public javax.swing.JTextField getTxtSaldoCuenta() {
        return txtSaldoCuenta;
    }

    /**
     * @param txtSaldoCuenta the txtSaldoCuenta to set
     */
    public void setTxtSaldoCuenta(javax.swing.JTextField txtSaldoCuenta) {
        this.txtSaldoCuenta = txtSaldoCuenta;
    }

    /**
     * @return the txtValor
     */
    public javax.swing.JTextField getTxtValor() {
        return txtValor;
    }

    /**
     * @param txtValor the txtValor to set
     */
    public void setTxtValor(javax.swing.JTextField txtValor) {
        this.txtValor = txtValor;
    }
}
